config/routes.rb
Rails.application.routes.draw do

  get 'ranking/index'

  namespace :admin do
    resources :pages
  end

  devise_for :users

  root to:'home#index'

  get  'contests/archive'
  get  '/contests'   => 'contests#list'
  get  'contests/:id' => 'contests#show', as: 'contest'
  get 'contests/hall_of_fame' => 'contests#hall_of_fame', as: 'hall_of_fame'

  resources :participants, except: [:destroy]

  get 'contests/open'
  get 'contests/show'

  get 'photographers/list', as: 'photographer_list'
  get 'photographers/:id' => 'photographers#show', as: 'photographer'

  get '/admin' => 'admin/home#index'

  namespace :admin do

    root to: 'home#index'
    get      'login'   => 'sessions#new'
    post     'login'   => 'sessions#create'
    delete   'logout'   => 'sessions#destroy'

    resources :contests

    get 'users/index'

    get      'participant/:id/:status'   => 'participants#update'
  end

  get ':permalink' => 'pages#route'
  get 'vote/:id' => 'votes#create'
end

app/views/admin/pages/_form.html.erb
<script type="text/javascript">
	$(function () {
  $('[data-toggle="popover"]').popover()
})
</script>
<%= simple_form_for @page, url: [:admin, @page] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :permalink %>
    <%= content_tag :button, 'Ajuda', class: 'btn btn-primary help-markdown', 
      type: 'button', 
      data: 
        { html: 'true', toggle: 'popover', 
          content: "<dl>
                      <dt>Negrito</dt>
                      <dd>**Exemplo de Negrito**</dd>
                      <dd><b>Exemplo de Negrito</b></dd>

                      <dt>Itálico</dt>
                      <dd>*Exemplo em Itálico*</dd>
                      <dd><i>Exemplo em Itálico</i></dd>

                      <dt>Itálico e Negrito</dt>
                      <dd>***Exemplo em Itálico e Negrito***</dd>
                      <dd><b><i>Exemplo em Itálico e Negrito</i></b></dd>

                      <dt>Links</dt>
                      <dd>[UTFPR](http://www.utfpr.edu.br/)</dd>
                      <dd><a href='http://www.utfpr.edu.br/'>UTFPR</a></dd>
                    </dl>

                    <p>Para mais informações exemplos acesse esse <a href='http://forum.techtudo.com.br/ajuda_markdown/' target='_blank'>tutorial</a></p>", 

          placement: 'left'}, 
      title: '<h4>Editor Markdown</h4>' %>

    <%= f.input :content, as: :text, input_html: { "data-provide" => "markdown", cols: 10, rows: 10 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<% provide(:title, "Ediçao de página") %>
<header class="without-background clearfix">
  <h1 class="text-left pull-left">Ediçao de Pagina</h1>
  <div class="pull-right">
    <%= link_to '', admin_pages_path, class: 'btn btn-primary btn-fab btn-raised mdi-navigation-arrow-back' %>
    <%= link_to '', admin_page_path(@page), class: 'btn btn-primary btn-fab btn-raised mdi-action-description' %>
  </div>
</header>

<br/>

<%= render 'form' %>

app/views/admin/pages/index.html.erb
<% provide(:title, "Listagem de Páginas") %>
<section>
  <header class="without-background clearfix">
    <h1 class="text-left pull-left">Listagem de Páginas</h1>
    <div class="pull-right">
      <%= link_to '', new_admin_page_path , class: 'btn btn-primary btn-fab btn-raised mdi-content-add'%>
    </div>
  </header>

  <br/>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
       <th><%= Page.human_attribute_name :name %></th>
       <th><%= Page.human_attribute_name :permalink %></th>
       <th colspan="2">Opções</th>
      </tr>
    </thead>

    <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.name, admin_page_path(page) %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to raw('<i class="mdi-content-create"></i>'), edit_admin_page_path(page) %></td>
        <td><%= link_to raw('<i class="mdi-content-clear"></i>'), admin_page_path(page), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</section>

app/views/admin/pages/new.html.erb
<% provide(:title, "Nova Página") %>
<header class="without-background clearfix">
  <h1 class="text-left pull-left">Nova Página</h1>
  <div class="pull-right">
    <%= link_to '', admin_pages_path, class: 'btn btn-primary btn-fab btn-raised mdi-navigation-arrow-back' %>
  </div>
</header>

<br/>

<%= render 'form' %>

app/views/admin/pages/show.html.erb
<% provide(:title, "Páginas") %>
<section>
  <header class="without-background clearfix">
    <h1 class="text-left pull-left"><%= @page.name %></h1>
    <div class="pull-right">
      <%= link_to '', admin_pages_path, class: 'btn btn-primary btn-fab btn-raised mdi-navigation-arrow-back' %>
      <%= link_to '', edit_admin_page_path(@page), class: 'btn btn-primary btn-fab btn-raised mdi-content-create' %>
    </div>
  </header>

  <br/>

  <article>
    <p>
      <strong><%= Page.human_attribute_name :permalink %>:</strong>
      <%= @page.permalink %>
    </p>

    <p>
      <strong><%= Page.human_attribute_name :content %>:</strong>
      <%= markdown @page.content %>
    </p>
  </article>
</section>