config/routes.rb
Rails.application.routes.draw do

  get 'ranking/index'

  namespace :admin do
    resources :pages
  end

  devise_for :users

  root to:'home#index'

  get  'contests/archive'
  get  '/contests'   => 'contests#list'
  get  'contests/:id' => 'contests#show', as: 'contest'
  get 'contests/hall_of_fame' => 'contests#hall_of_fame', as: 'hall_of_fame'

  resources :participants, except: [:destroy]

  get 'contests/open'
  get 'contests/show'

  get 'photographers/list', as: 'photographer_list'
  get 'photographers/:id' => 'photographers#show', as: 'photographer'

  get '/admin' => 'admin/home#index'

  namespace :admin do

    root to: 'home#index'
    get      'login'   => 'sessions#new'
    post     'login'   => 'sessions#create'
    delete   'logout'   => 'sessions#destroy'

    resources :contests

    get 'users/index'

    get      'participant/:id/:status'   => 'participants#update'
  end

  get ':permalink' => 'pages#route'
  get 'vote/:id' => 'votes#create'
end

app/models/admin/contest.rb
class Admin::Contest < ActiveRecord::Base
  validates :title,               presence: true
  validates :description,         presence: true  
  validates :opening_enrollment,  presence: true
  validates :closing_enrollment,  presence: true
  validates :opening,             presence: true
  validates :closing,             presence: true

  validates :opening_enrollment,   date: { after_or_equal_to: Time.now, before: :closing_enrollment }
  validates :opening,              date: { after_or_equal_to: Time.now, before: :closing }
  validates :closing,              date: { after_or_equal_to: Time.now }
  validates :closing_enrollment,   date: { after_or_equal_to: Time.now }

  has_attached_file :folder, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :folder, :content_type => /\Aimage\/.*\Z/

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  scope :closed_home, -> { where("closing < ?", Time.zone.now).limit(3) }
  has_many :participants
  has_many :users, through: :participants

  validates :title,               presence: true
  validates :description,         presence: true
  validates :opening_enrollment,  presence: true
  validates :closing_enrollment,  presence: true
  validates :opening,             presence: true
  validates :closing,             presence: true


  validates :opening_enrollment,   date: { after_or_equal_to: Time.now, before: :closing_enrollment }
  validates :opening,              date: { after_or_equal_to: Time.now, before: :closing }
  validates :closing,              date: { after_or_equal_to: Time.now }
  validates :closing_enrollment,   date: { after_or_equal_to: Time.now }


  has_attached_file(:image, {styles: { medium: "300x300>", thumb: "100x100>",
                                      large: "500x500>" }}.merge(PaperclipStorageOption.options))



  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def closed?
    self.closing < Time.zone.now
  end

  def open?
    self.opening <= Time.zone.now && self.closing >= Time.zone.now
  end

  def open_enrollment?
    self.opening_enrollment <= Time.zone.now && self.closing_enrollment >= Time.zone.now
  end

  # If current date is between closing enrollment and opening contest
  def idle?
    self.closing_enrollment <= Time.zone.now && self.opening >= Time.zone.now
  end

  def waiting?
    self.opening > Time.zone.now
  end

  def self.current
    current = where("opening <= ? AND closing >= ?", Time.zone.now, Time.zone.now).limit(1)
    if current.nil?
      current = where("opening_enrollment <= ? AND closing_enrollment >= ?", Time.zone.now, Time.zone.now).limit(1)
    end
    current.try(:first)
  end

  def self.list
    # open = where("opening <= ? AND closing >= ?", Time.zone.now, Time.zone.now)
    # open_enrollment = where("opening_enrollment <= ? AND closing_enrollment >= ?", Time.zone.now, Time.zone.now)
    # future = where("opening_enrollment > ?", Time.zone.now)
    contests = where("closing > ?", Time.zone.now).order(:opening)
  end

  def self.old
    contest = where("closing <= ?", Time.zone.now)
  end

  def self.opening_enrollment
    contests = where("opening_enrollment <= ? AND closing_enrollment >= ?", Time.zone.now, Time.zone.now)
  end

  def self.opening
    contests = where("opening <= ? AND closing >= ?", Time.zone.now, Time.zone.now)
  end

  def self.available
     contests = where("opening_enrollment <= ? AND closing >= ?", Time.zone.now, Time.zone.now)
  end

end

app/controllers/admin/contests_controller.rb
class Admin::ContestsController < Admin::ApplicationController
  #before_action :logged_in_user
  before_action :admin_user
  before_action :set_contest, only: [:show, :edit, :update, :destroy]
  before_action :approved_participants, only: [:show, :edit, :update, :destroy]
  before_action :not_approved_participants, only: [:show, :edit, :update, :destroy]
  before_action :rejected_participants, only: [:show, :edit, :update, :destroy]


  def index
    @contests = Contest.all
  end

  def show
    @contest = Contest.find_by_id(params[:id])
    @participants = Participant.approved.where(contest_id: @contest.id)
    if @contest.open?
      @partial_podium = @participants.joins("LEFT OUTER JOIN votes ON votes.participant_id = participants.id").group("participants.id").order("count(votes.participant_id) desc")
    end
    flash[:info] = "Ainda não existem inscrições aprovadas para este concurso." unless @participants.count > 0
    if @contest.closed?
      @podium = Participant.podium(@contest.id)
    end

  end

  def new
    @contest = Contest.new
  end

  def edit
  end

  def create
    @contest = Contest.new(contest_params)

    if @contest.save
      redirect_to admin_contest_path(@contest), notice: 'Contest was successfully created.'
    else
      render :new
    end
  end

  def update
    respond_to do |format|
      if @contest.update(contest_params)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contest.destroy
    redirect_to admin_contests_url, notice: 'Contest was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contest
      @contest = Contest.find(params[:id])
    end

    def approved_participants
      @approved_participants = Participant.approved.where(contest_id: @contest.id)
      flash[:info] = "Ainda não existem inscrições aprovadas para este concurso." unless @approved_participants.count > 0
    end

    def not_approved_participants
      @not_approved_participants = Participant.pending.where(contest_id: @contest.id)
      flash[:info] = "Existem #{@not_approved_participants.count} inscrições com aprovação pendende." if @not_approved_participants.count > 0
    end

    def rejected_participants
      @rejected_participants = Participant.failed.where(contest_id: @contest.id)
      flash[:info] = "Existem #{@rejected_participants.count} inscrições recusadas!." if @rejected_participants.count > 0
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contest_params
      params.require(:contest).permit(:title, :description, :image, :opening_enrollment, :closing_enrollment, :opening, :closing)
    end
  end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  #before_action :logged_in_user

  def list
    @current_user = current_user
    @contests = Contest.list.paginate(page: params[:page], per_page: 9)
  end

  def show
  	@contest = Contest.find_by_id(params[:id])
    @participants = Participant.approved.where(contest_id: @contest.id)
    if @contest.open?
      @partial_podium = @participants.joins("LEFT OUTER JOIN votes ON votes.participant_id = participants.id").group("participants.id").order("count(votes.participant_id) desc")
    end
    flash[:info] = "Ainda não existem inscrições aprovadas para este concurso." unless @participants.count > 0
    if @contest.closed?
      @podium = Participant.podium(@contest.id)
    end
  end

  def archive
  	@contests = Contest.old.paginate(page: params[:page], per_page: 9)
  end

  def hall_of_fame
    @photographers_first = User.order(first: :desc, second: :desc, third: :desc).limit(3)
    @photographers_last = User.order(first: :desc, second: :desc, third: :desc).limit(7).offset(3)
  end

  private

	# Check by user logged
	def logged_in_user
    store_location
    unless user_signed_in?
     flash[:danger] = "Efetue seu login para se inscrever no concurso!"
     redirect_to new_user_session_path
   end
  end

end

app/views/contests/_contest.html.erb
<li>
  <%= contest.title %>
</li>

app/views/contests/_participant.html.erb
  <a href="#" data-toggle="modal" data-target=#<%="modal-#{participant.id}"%> class="">
    <%= image_tag(participant.picture.url(:thumb), alt: participant.contest.title, class: "link-img img-responsive") unless participant.contest.image.blank? %> 
  </a>
  <% if(participant.contest.closed?) %>
    <p>Votos: <%= participant.votes.count unless !participant.contest.closed? %></p>
  <% end %>


<!-- Modal -->
<div class="modal fade" id="<%="modal-#{participant.id}"%>" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"><%=participant.title%></h4>
            </div>
            <div class="modal-body">
                <div class="row image">
                    <div class="col-xs-12">
                        <%= image_tag(participant.picture.url(:medium), alt: participant.contest.title, class: "img-responsive") unless participant.contest.image.blank? %> 
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-xs-3 col-sm-2">
                        <%= image_tag(participant.picture.url(:thumb), alt: participant.contest.title, class: "img-responsive") unless participant.contest.image.blank? %>
                    </div>
                    <div class="col-xs-9 col-sm-10">
                        <p>Fotógrafo(a): <%= participant.user.name %> </p>
                        <p>Descrição: <%=participant.description%></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <% if(participant.contest.closed?) %>
                    <p>Votos: <%= participant.votes.count unless !participant.contest.closed? %></p>
                <% else %>
                    <%= user_vote_pannel(participant) %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/contests/archive.html.erb
<% provide(:title, "Arquivos de Concursos") %>
<div class="container">
	<div class="row">
		<h2>Concursos antigos</h2>
			<% @contests.each do |contest| %>
				<%= link_to contest do %>
					<div class="col-md-4 col-md-4 col-xs-12">
						<div class="row">
							<div class="archive">
								<div class="col-xs-12 image">
									<%= image_tag(contest.image(:thumb) , alt: contest.title) %>
								</div>
								<div class="col-xs-12">
									<p class="title">
										<b><%= contest.title %></b>
									</p>
									<p class="close-at">Concurso encerrado há <%= format_date_old(contest.closing) %></p>
									<hr>
									<div class="winners">
									<% Participant.podium(contest.id).each_with_index do |participant, key|%>
										<p><%= key + 1 %>º <%=participant.user.name %></p>
									<% end %>
									</div>
								</div>
							</div>					
						</div>				
					</div>
				<% end %>
			<% end %>
		<div class="row">
			<div class="col-md-12 text-right">
				<%= will_paginate @contests, renderer: BootstrapPagination::Rails %>
				</div>
		</div>
	</div>
</div>

app/views/contests/hall_of_fame.html.erb
<% provide(:title, "Hall da fama") %>
<div class="container">
	<div class="row">
		<h2>Hall da fama</h2>
		<% @photographers_first.each.with_index do |photographer, index|%>
			<div class="col-md-12 col-xs-12">
				<div class="col-xs-6 col-sm-2">
					<a class="thumbnail">
				    	<%= gravatar_for photographer %>
				    </a>
				</div>
				<div class="col-sm-10 col-xs-6">
					<div class="col-md-2 col-xs-3 ">
						<% if index == 0 %>
							<i class="col-md-10 col-sm-6 col-xs-12 "><%= image_tag("first.png", alt: "Campeão", class: "img-responsive img-hall-position", title: "Campeão") %>
							</i>
						<% elsif index == 1 %>
							<i class="col-md-10 col-sm-6 col-xs-12"><%= image_tag("second.png", alt: "Vice-campeão", class: "img-responsive img-hall-position", title: "Vice Campeão") %>
							</i>
						<% elsif index == 2 %>
							<i class="col-md-10 col-sm-6 col-xs-12"><%= image_tag("third.png", alt: "Terceiro lugar", class: "img-responsive img-hall-position", title: "Terceiro") %>
	            			</i>
						<% end %>
					</div>
					<a href="#"><h3><%= index+1 %>. <%= link_to photographer.name, photographer_path(photographer.id) %></h3></a>
					<article class="small-description">
						<%= photographer.short_description%>
					</article>
				</div>
			</div>
		<% end; %>
	</div>
	<hr class="style-hr">
	<div class="row">
		<% @photographers_last.each.with_index do |photographer, index|%>
			<div class="col-md-12 col-xs-12">
				<div class="col-xs-3 col-sm-2 col-md-1">
					<a>
				    	<%= gravatar_for photographer, {size: 40} %>
				    </a>
				</div>
				<div class="col-sm-10 col-xs-9 col-md-11">
					<a href="#"><h3><%= index+4 %>. <%= link_to photographer.name, photographer_path(photographer.id) %></h3></a>
					<article class="small-description">
						<%= photographer.short_description%>
					</article>
				</div>
			</div>
		<% end; %>
	</div>
</div>

app/views/contests/list.html.erb
<% provide(:title, "Lista de Concursos") %>
<div class="container">
	<div class="row row-contests">
		<h2>Lista de Concursos</h2>
		<div class="col-xs-12">
			<% @contests.each do |contest| %>
				<div class="col-xs-12 col-sm-4 contest_show">
					<br/>
					<div class="col-xs-12 image">
						<a href="<%= contest_path(contest) %>" class="thumbnail">
							<%= image_tag(contest.image(:original), alt: contest.title, class: "img-responsive") unless contest.image.blank? %>
		    				<%= image_tag("placeholder.png", alt: "Placeholder", class: "img-responsive") unless contest.image.blank? == false %>
					    </a>
					</div>
					<div class="col-xs-12">
						<p class="title"><b><%= contest.title %></b></p>
						<p><%= contest_status_label(contest) %>
						<div class="fb-share-button" data-href="<%= contest_url(contest) %>" data-layout="button_count"></div></p>

						<p class="opening_enrollment">Início das Inscrições: <b> <%= contest.opening_enrollment.strftime("%d/%m/%Y - %H:%M") %></b></p>
						<p class="closing_enrollment">Término das Inscrições: <b> <%= contest.closing_enrollment.strftime("%d/%m/%Y - %H:%M") %></b></p>
						<p class="link_contest"><%= link_to "Visitar a página do concurso", contest %></p>


						<br>
					</div>
				</div>
			<% end %>
		<div class="row">
			<div class="col-md-12 text-right">
				<%= will_paginate @photographers, renderer: BootstrapPagination::Rails %>
			</div>
		</div>
		</div>
	</div>
</div>

app/views/contests/show.html.erb
<%
	provide(:title, "Detalhes do concurso")
	provide(:facebook_tags, create_facebook_meta_tag(@contest))
%>

<div id="contest" class="container">
	<div id="description" class="row">
		<div class="col-xs-12">
			<h2><%= @contest.title %></h2>
		</div>
	</div>
	<div id="new-contest" class="row">
		<div class="col-xs-12 col-sm-4">
			<a href="#" class="thumbnail">
				<%= image_tag(@contest.image(:original), alt: @contest.title, class: "img-responsive") unless @contest.image.blank? %>
		    	<%= image_tag("placeholder.png", alt: "Placeholder", class: "img-responsive") unless @contest.image.blank? == false %>
		    </a>
		    <ul class="list-group">
				<li class="list-group-item">Início das Inscrições: <%= @contest.opening_enrollment.strftime("%d/%m/%Y - %H:%M") %></li>
				<li class="list-group-item">Término das Inscrições: <%= @contest.closing_enrollment.strftime("%d/%m/%Y - %H:%M") %></li>
				<li class="list-group-item">Início da Votação: <%= @contest.opening.strftime("%d/%m/%Y - %H:%M") %></li>
				<li class="list-group-item">Término da Votação: <%= @contest.opening.utc.strftime("%d/%m/%Y - %H:%M") %></li>
			</ul>
		</div>
		<div class="col-xs-12 col-sm-8">
			<!-- <div class="well well-md"> -->
			    <div class="row">
			    	<div class="col-xs-12">
			    		<%= @contest.description %>
			    		<p><%= contest_status_label(@contest) %></p>
							<div
								class="fb-like"
								data-share="true"
								data-width="450"
								data-show-faces="true"
								data-href="<%= root_url + "/contest/#{@contest.id}" %>"
								>
							</div>


								<table class="table partial-podium">
									<tr>
										<th class="col-md-2">Posição</th>
										<th class="col-md-2">Foto</th>
										<th>Título</th>
										<th class="col-md-2">Voto(s)</th>
									</tr>
								<% if(@contest.open?) %>	
									<% @partial_podium.each_with_index do |participant, position| %>
										<tr>
											<td><%= "#{position+1}º" %></td>
											<td><%= link_to "#", data: {toggle: "modal", target: "#modal-#{participant.id}"}, class: "thumbnail" do %>
														<%= image_tag(participant.picture.url(:thumb), alt: participant.contest.title, class: "img-responsive") unless participant.contest.image.blank? %>
													<% end %>
											</td>
											<td><%= participant.title %></td>
											<td><%= pluralize(participant.votes.count, "voto") %></td>
										</tr>
									<% end %>
								</table>
			    		<% end %>
			    	</div>
					<div class="col-xs-12">
						<% if(@contest.open_enrollment?) %>
							<p>As inscrições estarão abertas por mais <%= format_date_old(@contest.closing_enrollment) %></p>
						<% end %>
						<p><%= contest_link_register(@contest) %></p>
					</div>

			    </div>
			<!-- </div> -->
		</div>
	</div>
	<% if @contest.open? %>
    <hr class="style-hr">
		<div class="show-pictures-contest">
      <h3>Todas fotos participantes</h3>
      <div class="row">
        <div class="container">
          <% @participants.each do |participant| %>
            <%= render 'participant', :participant => participant %>
          <% end %>
        </div>
      </div>
    </div>
	<% end %>
	<% if @contest.closed? %>
		<div class="row">
			<p>Primeiro lugar</p>
			<% if @podium[0].kind_of?(Array) %>
				<% @podium[0].each do |participant| %>
					<%= render 'participant', :participant => participant %>
		        <% end %>
		    <% else %>
				<%= render 'participant', :participant => @podium[0] %>
		    <% end %>
		</div>
		<div class="row">
			<p>Segundo lugar</p>
			<% if @podium[1].kind_of?(Array) %>
				<% @podium[1].each do |participant| %>
					<%= render 'participant', :participant => participant %>
		        <% end %>
		    <% else %>
				<%= render 'participant', :participant => @podium[1] %>
		    <% end %>
		</div>
		<div class="row">
			<p>Terceiro lugar</p>
			<% if @podium[2].kind_of?(Array) %>
				<% @podium[2].each do |participant| %>
					<%= render 'participant', :participant => participant %>
		        <% end %>
		    <% else %>
				<%= render 'participant', :participant => @podium[2] %>
		    <% end %>
		</div>
	<% end %>
</div>