config/routes.rb
Rails.application.routes.draw do

  get 'ranking/index'

  namespace :admin do
    resources :pages
  end

  devise_for :users

  root to:'home#index'

  get  'contests/archive'
  get  '/contests'   => 'contests#list'
  get  'contests/:id' => 'contests#show', as: 'contest'
  get 'contests/hall_of_fame' => 'contests#hall_of_fame', as: 'hall_of_fame'

  resources :participants, except: [:destroy]

  get 'contests/open'
  get 'contests/show'

  get 'photographers/list', as: 'photographer_list'
  get 'photographers/:id' => 'photographers#show', as: 'photographer'

  get '/admin' => 'admin/home#index'

  namespace :admin do

    root to: 'home#index'
    get      'login'   => 'sessions#new'
    post     'login'   => 'sessions#create'
    delete   'logout'   => 'sessions#destroy'

    resources :contests

    get 'users/index'

    get      'participant/:id/:status'   => 'participants#update'
  end

  get ':permalink' => 'pages#route'
  get 'vote/:id' => 'votes#create'
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  #Create Action beforeAction
  #  if user_signed_in? && current_user.admin?
  before_action :logged_in_user
  #before_action :correct_user
  before_action :admin_user

  def index
    @contests =  Contest.opening_enrollment
    @not_approved_participants = Participant.pending.where(contest_id: @contests.ids)
    @contests_opening = Contest.opening
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@current_contest = Contest.current
    @old_contests = Contest.closed_home
    @participants = Participant.where(status: 2).order(created_at: :desc).limit(10)

  end
end

app/views/admin/home/index.html.erb
<% provide(:title, "Página Inicial") %>


<div class="row index-page-admin">
  <div class="col-md-4">
    <div class="panel panel-info contest-open">
	     <div class="panel-heading">Concursos Abertos</div>
	      <div class="panel-body">
          <table class="table table-striped table-hover">
            </thead>
              <tbody>
                <% @contests.each do |contest| %>
                  <tr>
                    <td><%= link_to contest.title, admin_contest_path(contest) %></td>
                  </tr>
                <% end %>
              </tbody>
          </table>
        </div>
    </div>
  </div>

  <div class="col-md-4">

    <div class="panel panel-info approved-pictures">
	     <div class="panel-heading">Fotos para Aprovação</div>
	      <div class="panel-body">
          <table class="table table-striped table-hover">
              <tbody>

                  <% @not_approved_participants.each do |participant| %>
                  <tr>
                    <td>
                      <%= link_to participant.title, 'javascript:void(0)',
                        data:{toggle: "modal", target: "#modal-#{participant.id}"}%>
                    </td>
                  </tr>
    <!-- Modal -->

                <%= render 'shared/approved_pictures', :participant => participant %>

                <% end %>
              </tbody>
          </table>
        </div>
    </div>
  </div>

  <div class="col-md-4">

    <div class="panel panel-info ranking">
	     <div class="panel-heading">Ranking de Concursos</div>
	      <div class="panel-body">
          <table class="table table-striped table-hover">
              <tbody>
                <% @contests_opening.each do |contest| %>
                  <tr>
                    <td><%= link_to contest.title,  admin_contest_path(contest) %>	</td>
                  </tr>
                <% end %>
              </tbody>
          </table>
        </div>
    </div>

</div>

  </div>
</div>